const data = [
  {
    id: 83,
    title: "El pulpo cocinero",
    portada: "https://drive.google.com/uc?export=download&id=1bPAqpgkIW5Zl_3Hd5UdcxBNWM6VtVBcD",
    interior: {
      interior1: "https://drive.google.com/uc?export=download&id=1bs4R0oC9Jvk5umSGzEaVeiDro2JmMU8U",
    },
    alt: "El Pulpo Cocinero",
  },
  {
    id: 84,
    title: " Proyecto Personal 1",
    src: "https://drive.google.com/uc?export=download&id=",
    interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 85,
    title: "Proyecto Personal 2",
    src: "https://drive.google.com/uc?export=download&id=",
    interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 86,
    title: "Abanico",
    src: "https://drive.google.com/uc?export=download&id=",
    interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 87,
    title: "Proyecto Personal 3",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 88,
    title: "Coronados de gloria",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 89,
    title: "Señora y flor",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 90,
    title: "Va a llover",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 91,
    title: "Proyecto personal 5",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 92,
    title: "Fanzine: Para ver mejor",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 93,
    title: "¿Por Qué?¿Por Qué?",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 94,
    title: "Sra. Parsimonia",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 95,
    title: "Tinta Negra",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 96,
    title: "Acá tá",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 97,
    title: "Un remolino",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 98,
    title: "Desde la Raíz",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
  {
    id: 99,
    title: "Proyecto Personal 4",
    src: "https://drive.google.com/uc?export=download&id=",
        interior: {
      interior1: "",
      interior2: "",
      interior3: "",
      interior4: "",
      interior5: "",
      interior6: "",
      interior7: "",
      interior8: "",
      interior9: "",
    },
    alt: "",
  },
];
